### ISSUE TITLE
Unable to enable enhanced monitoring for RDS

### ISSUE THREAD

**Issue by ccostino** [fecgov/fec-infrastructure#35]
We have tried numerous times to get enhanced monitoring and logging activated via Terraform for the RDS instances, yet we have been unsuccessful each time.  We have gotten as far as creating the role and policy successfully itself, but not associated it with the RDS instances.

What ends up happening is this:

```
InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0.
```

However, we are supplying that with the `monitoring_role_arn` parameter, and it seems to be ignored.

Is it possible that there is a `tfstate` file is causing an issue here?  Are we going to have to undo and redo all of the setup again like what is described [here](https://github.com/hashicorp/terraform/issues/9435#issuecomment-266788636) (already went through this exercise once)?

@LinuxBozo and/or @jmcarp, do you have any ideas what is taking place?

**Comment by ccostino** [comment]
In looking at the last Terraform build we do see it's pulling in a `tfstate` file, so I am guessing that's the culprit, but neither of us are entirely sure.

**Comment by ccostino** [comment]
We got it working by resetting the `tfstate` file, thanks!

**Comment by s-nakka** [comment]
I see same issue in TF 0.11.3

**Comment by alanlok** [comment]
The problem continues to persist in TF 0.11.10 / AWS Provider 1.52 when you are modifying an existing RDS instance to enable enhanced monitoring. However following the steps in this comment will provide a sufficient workaround:

https://github.com/hashicorp/terraform/issues/9435#issuecomment-266788636
