### ISSUE TITLE
move continuous deployment from Concourse

### ISSUE THREAD

**Issue by afeld** [fecgov/fec-infrastructure#43]
Cloud.gov is moving away from offering Concourse to tenants, so need to move to something else. CircleCI is the obvious choice, since it's a) approved under the IT Standards Profile, and b) already in use for this repository for continuous integration.

[Example pull request from TTS DNS repo doing this recently.](https://github.com/18F/dns/pull/178)

1. [x] Pause Concourse deployment pipeline
1. [x] Add `terraform apply` to `.circleci/config.yml`
1. [x] Add necessary environment variables to CircleCI project
1. [x] Push config change up to GitHub
1. [x] Confirm that `terraform apply` completes successfully
1. [ ] Remove pipeline from Concourse
1. [ ] Disable Concourse service from cloud.gov account
    * May need to ask #cg-support to do this for you
1. [x] Remove `credentials.example.yml` and `pipeline.yml` from repository

**Comment by ccostino** [comment]
@afeld and @LindsayYoung, I merged the other PR related to this, it looks like we're all done here, right?  Or is there more left to do?

**Comment by ccostino** [comment]
Oh, perhaps disabling the service itself?  When would be a good time to do that, if we haven't already?  Being sensitive to the cloud.gov team's availability at the moment given this week's events.

**Comment by afeld** [comment]
Go for it! You might be able to do the remaining tasks yourself with`fly destroy-pipeline` and `cf delete-service-instance`, respectively.

**Comment by ccostino** [comment]
Awesome!

@LindsayYoung were you able to remove the pipeline already?

@afeld is `cf delete-service-instance` what you would run in the org associated with the pipeline once the pipeline itself is destroyed?

**Comment by afeld** [comment]
@ccostino I believe so, yes.

**Comment by afeld** [comment]
Small nudge on finishing this up.

**Comment by ccostino** [comment]
D'oh thanks for the reminder, @afeld!

**Comment by LindsayYoung** [comment]
I ran the command to remove the pipeline but it was on the day of the cloud.gov errors so I was not sure it took, is that something you can confirm @afeld?

**Comment by afeld** [comment]
Sounds like cloud.gov is going to take care of it, per [Slack convo](https://gsa-tts.slack.com/archives/C17Q2LC9W/p1517608298000511?thread_ts=1517604979.000442&cid=C17Q2LC9W). @brittag Let us know when we can close!

**Comment by LindsayYoung** [comment]
Britta said the cloud.gov team is going to do the clean up steps so we are good! 

Thanks again @afeld
