### ISSUE TITLE
Upgrade PostgreSQL instances in RDS to latest stable release

### ISSUE THREAD

**Issue by ccostino** [fecgov/fec-infrastructure#47]
AWS has recently updated the version of PostgreSQL supported for RDS to the latest stable release.  We should set aside time to perform an update, which will require modifying the Terraform file to set each instance to the newest available version.

We'll want to do this off-hours as it will result in a brief moment of downtime for each instance.

**Comment by AmyKort** [comment]
@PaulClark2 and @jwchumley , do you know where we're at with this?

**Comment by ccostino** [comment]
I've updated this ticket in anticipation for PI 6 and the fact that AWS RDS supports version 10.1 now!
