### ISSUE TITLE
Instances with higher network performance

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/fec-infrastructure#50]
Research switching RDS instances with higher network performance. This could be the issue with the replica lag. I asked devops guild about it and Adam suggested this. 

He agreed that the IOPS looked ok for the 2-week period we were looking at. Though that might be an issue again in the future.

**Comment by ccostino** [comment]
@LindsayYoung: Ah, so instead of the memory optimized instance classes, the network enhanced instance classes?

**Comment by rjayasekera** [comment]
All RDS replicas upgraded to db.r4.8xlarge
