### ISSUE TITLE
Research on adding more storage space for RDS in AWS

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/fec-infrastructure#51]
The size allocated for the DEV/STG/PRD database in AWS is 2TB.  Currently the database size is approaching 1.7TB.  More storage space is needed.  Research on how much more space is needed and the cost required.

**Comment by fecjjeng** [comment]
We can use the https://calculator.s3.amazonaws.com/index.html to help figure this out.

**Comment by fecjjeng** [comment]
The current settings (2 TB with IOPS 13000)

<img width="1134" alt="current_setting" src="https://user-images.githubusercontent.com/24943130/40213735-0e066b58-5a25-11e8-910b-853a8a9c22b7.png">

**Comment by fecjjeng** [comment]
The price with increased storage (2.5 TB with IOPS 15000)

<img width="1120" alt="increase_to_2 5t" src="https://user-images.githubusercontent.com/24943130/40213779-498dc82e-5a25-11e8-86c0-4e75724d05d5.png">

**Comment by fecjjeng** [comment]
Above is price calculated by the Amazon calculator. The increase of 500G of space across all the 6 instances, also with the increase storage, more IOPS need to keep similar IOPS to Storage ratio (AWS recommand 3:1 to 10:1 ratio) for the production databases (the dev and stage does not use provisioned IOPS) will increase the monthly payment from $13055.75 to $14420.56 (i.e. $1364.81 increase).

**Comment by fecjjeng** [comment]
The price with increased storage (2.2 TB with IOPS 14000)

<img width="988" alt="increase_to_2 2t" src="https://user-images.githubusercontent.com/24943130/40231650-eaae9fdc-5a69-11e8-8a0f-a4279850e826.png">

**Comment by fecjjeng** [comment]
Above is price calculated by the Amazon calculator. 

The increase of 200G of space across all the 6 instances, also with the increase storage, more IOPS need to keep similar IOPS to Storage ratio (AWS recommand 3:1 to 10:1 ratio) for the production databases (the dev and stage does not use provisioned IOPS) will increase the monthly payment from $13055.75 to $13683.89 (i.e. $628.24 increase).

The increase of 500G of space across all the 6 instances, also with the increase storage, more IOPS need to keep similar IOPS to Storage ratio (AWS recommand 3:1 to 10:1 ratio) for the production databases (the dev and stage does not use provisioned IOPS) will increase the monthly payment from $13055.75 to $14420.56 (i.e. $1364.81 increase).

**Comment by rjayasekera** [comment]
New size is 2.5 TB
