### ISSUE TITLE
Create RDS replica 2 using terraform and define default zone

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-infrastructure#57]
replica_2 was removed manually removed from production. We need to recreate it using terraform and in addition, we need to create it in a different default zone. 

**Completion criteria:**
- [x] Researching utilizing `availability_zone = "${var.rds_az2}"` variable to create a default zone for RDS replica 2
- [x] Check to make sure rds_production_replica_2 is correct
- [ ] Submit PR for review here
- [x] Merge and double check that the build succeeds in AWS console
- [x] Change prod environmental variables to reference replica_2 (instructions here: https://github.com/fecgov/openFEC/wiki/switch-out-cf-service-environment-variables)
- [x] Back-up and delete replica_3

**Comment by rjayasekera** [comment]
- prod-replica-2 created using https://github.com/fecgov/fec-infrastructure/blob/master/terraform/fec_rds.tf 
- prod-replica-3 backup and deleted
- Modify environmental variable to point all API to replica-1 and replica-2
