### ISSUE TITLE
Set up route53 in AWS commercial

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-infrastructure#58]
The first step in transferring DNS records to FEC is to create our own route53 within our AWS commercial account. 

**Completion criteria:**
- [x] Create Route 53 in AWS east
- [ ] Create IAM role to allow provisioning of Route 53 records

**Comment by wjiangFEC** [comment]
I have create hosted zone in FEC's commercial account AWS Route 53 service.

Friday 10/5/2018 I requested a ticket with CenturyLink to delegate subdomain stage.fec.gov to AWS and send the AWS DNS server names to Centurylink.  It takes about two days over the weekend for Centurylink's update to propagate and take effect.  Now stage.fec.gov is resolved to AWS DNS servers.  You can check with: dig +trace stage.fec.gov

In order for the cloudfront to work with stage.fec.gov, Certificate needs to be requested or imported.  I will reach out to Centurylink to see if we already have certificate for stage.fec.gov.  We can request certificate from AWS certificate manager if Centurylink does not have one already.

**Comment by wjiangFEC** [comment]
I have configured AWS Route53 to host domain www.stage.fec.gov points to a static test web page hosts in S3, also set up CloudFront distribution for the static test website using AWS certificate.  We need to create the CloudFront distribution in cloud.gov for staging application and change www.stage.fec.gov to point the stage CloudFront distribution.  Also, need to remove the www.stage.fec.gov hosted zone record and create it using terraform.  Below is the reference from previous terraform file for transition.fec.gov or open.fec.gov, etc.

https://github.com/18F/dns/blob/master/terraform/transition.fec.gov.tf

**Comment by rjayasekera** [comment]
https://stage.fec.gov/ - created and pointing to https://fec-stage-proxy.app.cloud.gov/
Cloudfront distribution created for static content
