### ISSUE TITLE
Set up stage DNS entry for Web instances

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-infrastructure#59]
As an initial step to figuring out how to set up a new DNS entry under our own route53, we have identified creating the stage.fec.gov DNS entry first for practice. This will also enable us to use the same caching mechanisms that we have set up in production.

**Completion criteria:**
- [x] Check to see if FEC has created the stage.fec.gov DNS entry via our hosting provider
- [x] Adjust CircleCI config to deploy additional terraform files
- [x] Create workflows that include `plan`, `hold`, and `deploy` steps within our circle config
- [x] Create terraform within our fec-infrastructure repo in order to create a new DNS entry
- [x] Set up cdn-route service for new stage DNS entry
- [x] Retrieve new name servers and have hosting provider delegate authority to them. May take 24/48 hours to propagate.

**Comment by rjayasekera** [comment]
This task is completed
https://github.com/fecgov/fec-dns
