### ISSUE TITLE
Rebuild govcloud RDS instances to original settings

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-infrastructure#61]
We need to create RDS read replica 2 using terraform. Then point the SQLA_FOLLOWERS back to replica 2.

DO THIS OFF HOURS!

**Completion Criteria:**
- [x] Run terraform script to reapply replica 2
- [x] If disaster happens, recreate replica 2 manually through govcloud
- [x] Change SQLA_FOLLOWERS to point to replica 2
- [x] Delete replica 3

**Comment by rjayasekera** [comment]
This task is completed.
