### ISSUE TITLE
Create FEC owned DNS entries for API (open.fec.gov)

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-infrastructure#74]
We will create our own https://api.open.fec.gov and https://api-stage.open.fec.gov domain names using terraform.

This domains are for our production and stage API pointing to data.gov (api umbrella) for caching and management purposes.

Related issues: 
[https://github.com/fecgov/fec-infrastructure/issues/59](https://github.com/fecgov/fec-infrastructure/issues/59)
[https://github.com/fecgov/openFEC/issues/3293](https://github.com/fecgov/openFEC/issues/3293)

**Comment by lbeaufort** [comment]
Waiting for 18F to delete their terraform file

**Comment by rjayasekera** [comment]
18F deleted open.fec.gov entries from their servers - we can close this issue now
https://github.com/18F/dns/pull/346

My only concern going forward is that, our https certificates automatically get renewed. 

API https certificates 18F obtained from; comodoca.com (https://www.comodoca.com/en-us/) and they fee based.
All other App server https certificates 18F obtained from: Lets Encrypt (https://letsencrypt.org/) and those certificates are free.
