### ISSUE TITLE
Change remaining DB server machine classes to db.r4.2xlarge

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-infrastructure#76]
Move remaining AWS RDS servers to newer version of server class.

DB Instance | Old Server Class | New Server Class
------------ | ---------------- | ------------------
fec-govcloud-dev | db.r3.2xlarge | db.r4.2xlarge
fec-govcloud-dev-replica-1 | db.r3.2xlarge | db.r4.2xlarge
fec-govcloud-stage | db.r3.2xlarge | db.r4.2xlarge
fec-govcloud-prod | db.r3.2xlarge | db.r4.2xlarge

Following servers are already moved to or running on  `db.r4.8xlarge` server class as of 7/16/19
- fec-govcloud-stage-replica-1
- fec-govcloud-prod-replica-1
- fec-govcloud-prod-replica-2

**Comment by dorothyyeager** [comment]
PR was merged; closing this issue.
