### ISSUE TITLE
Synchronize terraform "state" file

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-infrastructure#82]
**What we're after:**
We need to make sure the terraform state file is up-to-date and matching across all 3 environments for easier database creation and maintenance.

Completion criteria:
- [x] Make sure the state file is sychronized across all 3 environments

**Comment by fec-jli** [comment]
We have checked terraform state file which synchronize with resources in stage space.
Notes to create test replica in the future:
**Method 1 --use terraform**
1) add new test replica section in fec_rds.tf,  set deletion_protection = true, merge PR(the first PR)
2) after testing, if want to remove replica. create second PR to deletion_protection = false
3) remove test replica section in fec_rds.tf, create the third PR, merge it.
4) check terraform state file in s3 bucket (under tts-fec folder)


**Method 2 --through aws console**
create and delete replica-2 from console. no change on fec_rds.tf

**unlock/lock deploy user account**
make sure to unlock deploy user account before merge and lock deploy user account back after merge is successful.

**Comment by rjayasekera** [comment]
After we delete the temporary replica (stage-replica-2) now the terraform state file is in-sync with the terraform.tf file in github.  We verify this by looking at the terraform state file in S3 bucket.  
This ticket can be closed.
